on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - run: go vet ./...
      # Build test examples
      - run: cd examples/terminal-multiplexer && go build .
      - run: cd examples/terminal-simple && go build .